#pragma once

#ifndef NMSP_PROFILER_CUSTOM_TRAITS
	#define NMSP_PROFILER_CUSTOM_TRAITS 0
#endif // 0

#ifndef NMSP_ENABLE_PROFILER
	#define NMSP_ENABLE_PROFILER 0
#endif // !NMSP_ENABLE_PROFILER
