#pragma once

#ifndef NMSP_JOB_SYSTEM_CUSTOM_TRAITS
	#define NMSP_JOB_SYSTEM_CUSTOM_TRAITS 0
#endif // 0


#ifndef NMSP_JOB_SYSTEM_MAX_FRAME_IN_FLIGHT_COUNT
	#define NMSP_JOB_SYSTEM_MAX_FRAME_IN_FLIGHT_COUNT	4
#endif

#ifndef NMSP_JOB_SYSTEM_LOGICAL_THREAD_COUNT
	#define NMSP_JOB_SYSTEM_LOGICAL_THREAD_COUNT		16
#endif

#define NMSP_JOB_SYSTEM_ENABLE_DEPENDENCY_MANAGER 0

#ifndef NMSP_JOB_SYSTEM_DEVELOPMENT
	#define NMSP_JOB_SYSTEM_DEVELOPMENT 1
#endif // 

