#pragma once

#ifndef NMSP_JOB_SYSTEM_CUSTOM_TRAITS
	#define NMSP_JOB_SYSTEM_CUSTOM_TRAITS 0
#endif // 0

#define NMSP_JOB_SYSTEM_MAX_FRAME_IN_FLIGHT_COUNT	4
#define NMSP_JOB_SYSTEM_LOGICAL_THREAD_COUNT		16

#define NMSP_JOB_SYSTEM_ENABLE_DEPENDENCY_MANAGER 0
#define NMSP_JOB_SYSTEM_DEBUG_CHECK 1

#define NMSP_JOB_SYSTEM_DEVELOPMENT 1